### ISSUE TITLE
✔️   레거시 수정 사항에 대한 테스트 코드 작성

### ISSUE THREAD

**Issue by ChooSeoyeon** [FISOLUTION/police-backend#22]
## 📌 Feature Issue
- 레거시에 수정을 가한 부분들에 대한 테스트 코드를 작성한다.

## 📝 To-do
- [ ] #3 에 대한 테스트 코드 작성
- [ ] #8 에 대한 테스트 코드 작성
- [ ] #17 에 대한 테스트 코드 작성
- [ ] #21 에 대한 테스트 코드 작성
